services:
  wp-db:
    image: mariadb:11
    container_name: wp-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - ./conf-cms-cliente2/wp-conf/mysql-data:/var/lib/mysql
    networks:
      isp_network:
        ipv4_address: 172.25.2.7
  wp-cliente2:
    build: 
      context: ./conf-cms-cliente2
      dockerfile: Dockerfile
    container_name: wp-cliente2
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_BASE_DOMAIN: wp.bacalhau.asa.isp
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: admin123
      WORDPRESS_ADMIN_EMAIL: admin@asa.isp
      WORDPRESS_SITE_TITLE: "Minha Rede"
    depends_on:
      - wp-db
    networks:
      isp_network:
        ipv4_address: 172.25.2.6
