services:
  wp-db-3:
    image: mariadb:11
    container_name: wp-db-3
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - ./conf-cms-cliente3/wp-conf/mysql-data:/var/lib/mysql
    networks:
      isp_network:
        ipv4_address: 172.25.3.7
  wp-cliente3:
    build: 
      context: ./conf-cms-cliente3
      dockerfile: Dockerfile
    container_name: wp-cliente3
    environment:
      WORDPRESS_DB_HOST: wp-db-3:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_BASE_DOMAIN: wp.piaba.asa.isp
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: admin123
      WORDPRESS_ADMIN_EMAIL: admin@asa.isp
      WORDPRESS_SITE_TITLE: "Rede Piaba"
    depends_on:
      - wp-db-3
    networks:
      isp_network:
        ipv4_address: 172.25.3.6
